### ISSUE TITLE
wrong source maps on font awesome scss

### ISSUE THREAD

**Issue by sormy** [medialize/sass.js#68]
Small and tiny sample to reproduce bug:

```scss
$fa-css-prefix: fa;

.#{$fa-css-prefix}-google-plus-circle:before,
.#{$fa-css-prefix}-google-plus-official:before { font-weight: bold; }
.#{$fa-css-prefix}-fa:before,
.#{$fa-css-prefix}-font-awesome:before { font-weight: bold; }
```

```html
        <div>
          Font Awesome: <i class="fa fa-font-awesome" aria-hidden="true"></i>
        </div>
```

Will generate source map for `.fa-font-awesome` element which point to line 4 of source code but it should point to line 5 (or 6). If you will comment `.#{$fa-css-prefix}-google-plus-circle:before,` it will start to generate correct source map. If you will replace `#{$fa-css-prefix}` with actual value `fa` then it will start to generate correct source map too.

Not sure if it libsass issue or sass.js

sass.js@0.9.13
