### ISSUE TITLE
Comments in the wrong place

### ISSUE THREAD

**Issue by babobski** [medialize/sass.js#75]
I'm maintaining the sass compiler addon for Komodo Ide, I got an issue reported about compiling comments in a weird way.

When you compile this piece of scss:

```scss
$main: #333;
$accent: #555;

#content .LightBlueContent,
#content .DarkBlueContent,
footer{
  /* Make the links match the page colours */
  /*Standard colours*/
  a:link, a:visited{ color: white;} /*Normal*/
  a:hover, a:active{ color: #ccc;} /*Hover*/ 

  /*Bullet point colours*/
  div.dl{color: white;}

  /*Button styling */
  .wButton:not(.sButton) span,
  .webeditShareComponent button > span{
    background: white;
    color: $main;
    text-shadow: none;
    transition: 0.5s;
    padding: 5px 10px;
    text-transform: uppercase;
    border-radius: 0;
    border: none;
  }

  .wButton:not(.sButton):hover span,
  .webeditShareComponent:hover button > span{
    background: white;
    color: $accent; 
  }
}
```

The outputted css:
```css
#content .LightBlueContent,
#content .DarkBlueContent,
footer {
  /* Make the links match the page colours */
  /*Standard colours*/
  /*Normal*/
  /*Hover*/
  /*Bullet point colours*/
  /*Button styling */
}

#content .LightBlueContent a:link, #content .LightBlueContent a:visited,
#content .DarkBlueContent a:link,
#content .DarkBlueContent a:visited,
footer a:link,
footer a:visited {
  color: white;
}

#content .LightBlueContent a:hover, #content .LightBlueContent a:active,
#content .DarkBlueContent a:hover,
#content .DarkBlueContent a:active,
footer a:hover,
footer a:active {
  color: #ccc;
}

#content .LightBlueContent div.dl,
#content .DarkBlueContent div.dl,
footer div.dl {
  color: white;
}

#content .LightBlueContent .wButton:not(.sButton) span,
#content .LightBlueContent .webeditShareComponent button > span,
#content .DarkBlueContent .wButton:not(.sButton) span,
#content .DarkBlueContent .webeditShareComponent button > span,
footer .wButton:not(.sButton) span,
footer .webeditShareComponent button > span {
  background: white;
  color: #333;
  text-shadow: none;
  transition: 0.5s;
  padding: 5px 10px;
  text-transform: uppercase;
  border-radius: 0;
  border: none;
}

#content .LightBlueContent .wButton:not(.sButton):hover span,
#content .LightBlueContent .webeditShareComponent:hover button > span,
#content .DarkBlueContent .wButton:not(.sButton):hover span,
#content .DarkBlueContent .webeditShareComponent:hover button > span,
footer .wButton:not(.sButton):hover span,
footer .webeditShareComponent:hover button > span {
  background: white;
  color: #555;
}
```

Expected result:

```css
/* Make the links match the page colours */
/*Standard colours*/
/*Normal*/
#content .LightBlueContent a:link, #content .LightBlueContent a:visited,
#content .DarkBlueContent a:link,
#content .DarkBlueContent a:visited,
footer a:link,
footer a:visited {
  color: white;
}

/*Hover*/
#content .LightBlueContent a:hover, #content .LightBlueContent a:active,
#content .DarkBlueContent a:hover,
#content .DarkBlueContent a:active,
footer a:hover,
footer a:active {
  color: #ccc;
}

/*Bullet point colours*/
#content .LightBlueContent div.dl,
#content .DarkBlueContent div.dl,
footer div.dl {
  color: white;
}

/*Button styling */
#content .LightBlueContent .wButton:not(.sButton) span,
#content .LightBlueContent .webeditShareComponent button > span,
#content .DarkBlueContent .wButton:not(.sButton) span,
#content .DarkBlueContent .webeditShareComponent button > span,
footer .wButton:not(.sButton) span,
footer .webeditShareComponent button > span {
  background: white;
  color: #333;
  text-shadow: none;
  transition: 0.5s;
  padding: 5px 10px;
  text-transform: uppercase;
  border-radius: 0;
  border: none;
}

#content .LightBlueContent .wButton:not(.sButton):hover span,
#content .LightBlueContent .webeditShareComponent:hover button > span,
#content .DarkBlueContent .wButton:not(.sButton):hover span,
#content .DarkBlueContent .webeditShareComponent:hover button > span,
footer .wButton:not(.sButton):hover span,
footer .webeditShareComponent:hover button > span {
  background: white;
  color: #555;
}

```
